# remote_theme: pages-themes/minimal@v0.2.0
# theme: jekyll-theme-minimal
# remote_theme: b2a3e8/jekyll-theme-console
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

header_pages:
  - index.md
  - about.md
  - README.md

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you have one

include:
  - README.md

defaults:
  - scope:
      path: "README.md"
    values:
      layout: default
      title: README
      permalink: "/readme/"



