# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: b2a3e8/jekyll-theme-console
header_pages:
  - index.md
  - about.md
  - README.md

style: hacker #dark # dark (default), light or
listen_for_clients_preferred_style: true # false (default) or true

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you have one

include:
  - README.md

defaults:
  - scope:
      path: "README.md"
    values:
      layout: default
      title: README
      permalink: "/readme/"



