remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you have one

include:
  - README.md

defaults:
  - scope:
      path: "README.md"
    values:
      layout: default
      title: README
      permalink: "/readme/"



