### url: https://delphym.github.io
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: b2a3e8/jekyll-theme-console
## https://github.com/pages-themes/hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

include:
  - README.md
  # - LICENSE.md

collections:
  blog:
    output: true
    permalink: /blog/:name.html ## /blog/:year/:month/:day/:title.html/
    # Optional: specify a custom layout
    layout: default
  # reflections:
  #   output: true
  #   permalink: /reflections/:name.html/
  # Optional: specify a custom layout
  # layout: post  # default

defaults:
  - scope:
      path: 'README.md'
    values:
      layout: default
      title: :README
      permalink: '/readme/'
  - scope:
      path: 'LICENSE.md'
    values:
      layout: default
      title: :LICENSE
      permalink: '/license/'

exclude:
  - .github
